### ISSUE TITLE
Add QR code reader

### ISSUE THREAD

**Issue by llewelld** [llewelld/harbour-contrac#3]
In order to register a positive diagnosis the app will need to be able to read QR codes.

**Comment by Thaodan** [comment]
https://github.com/ftylitak/qzxing/blob/master/examples/QZXingLive/main.qml
Could be a good start, its already used in sailotp.

**Comment by llewelld** [comment]
A good suggestion. Thanks!

**Comment by simonschmeisser** [comment]
there are unfortunately many forks and versions of zxing for C++ but https://github.com/nu-book/zxing-cpp is most active and I'd recommend it instead. I used it for orka/orca, a barcode reading app for plasma mobile. Feel welcome to copy paste code there (we can relicense stuff if needed)

**Comment by Thaodan** [comment]
Does it has a qml interface?
QZXing is not as active but has a very good QML interface and allows much 
easier integration.

**Comment by bionade24** [comment]
I mostly finished writing the GUID support, so that the Information from the QR codes can get processed. https://github.com/llewelld/harbour-contrac/pull/73  
For now, you will have to put in the GUID manually.  

If you don't want to argue about the QR-Code reader code, it could also be possible to let contrac open URLs, people then can choose a existing QR Code reader for Sailfish and then open the URL with contrac. 

For reference, QR Code and GUID localhost URL look like this: https://github.com/llewelld/harbour-contrac/issues/64#issue-731527186
