### ISSUE TITLE
Request for adding support

### ISSUE THREAD

**Issue by vladislavivanistsev** [llewelld/harbour-contrac#37]
Could you please add support for Estonian app HOIA https://www.hoia.me/en/?

**Comment by llewelld** [comment]
Thanks for flagging this up. The source code is available here:

https://koodivaramu.eesti.ee/tehik/hoia

It looks like it's using the DP-3T SDK rather than the Apple/Google Exposure Notification API, so this would need a bit more work than just switching the servers. As I understand it the two are quite similar though (although it's not something I've looked into personally).

**Comment by vladislavivanistsev** [comment]
The support answered that HOIA can not communicate with the harbour-contrac. Unfourtunately.
