### ISSUE TITLE
Unable to enter/submit longer Token from QR-Code.

### ISSUE THREAD

**Issue by bionade24** [llewelld/harbour-contrac#64]
![corona-form](https://user-images.githubusercontent.com/42534613/97548912-0acc8680-19d0-11eb-971e-16ad66d941fd.jpeg)
This the form you currently get to use with the Corona-Warn-App. TeleTAN is afaik deprecated, now you get a longer token like the one under the QR Code. This longer token can't be submitted in the current form. The blacked digits are like the one before them, 4 digits long. The QR code tries to open an URL in this format `https://localhost?token-from-below-the-qr-code`

**Comment by bionade24** [comment]
Sorry, accidentally clicked wrong when scanner closed, description will come in minutes.

**Comment by bionade24** [comment]
In the documentation, they're called `GUID` just in case it wasn't documented already anywhere else in the issues here. https://github.com/corona-warn-app/cwa-verification-server/blob/master/docs/architecture-overview.md#core-entities

**Comment by llewelld** [comment]
I could be mistaken, but following the original documentation, it suggested that either the QR code or a TeleTAN could be used, but there's an important difference:-

1. The QR code is scanned *before* you get your result. The official app then periodically checks online for the result of your test.
2. The TeleTAN is provided only once the result of the test is available (usually by phone when you call to get the result).

I only implemented 2 because 1 was more complex to implement and also much harder for me to test.

Are you certain that 2 has been deprecated? Or could it just be that you need to await the result before you can get hold of a TeleTAN? If indeed they have been deprecated, then I'd certainly have to look into implementing 1.

Thanks for your input here, it's really appreciated. I hope your result is negative.

Another important point is that if you've been using Contrac, you should avoid scanning the QR code on an Android device that you've not been using, since this could result in the wrong keys being uploaded to the server.

**Comment by bionade24** [comment]
> I could be mistaken, but following the original documentation, it suggested that either the QR code or a TeleTAN could be used, but there's an important difference:-
> 
> 1. The QR code is scanned _before_ you get your result. The official app then periodically checks online for the result of your test.
> 2. The TeleTAN is provided only once the result of the test is available (usually by phone when you call to get the result).

I figured that out after I wrote my first comment, yes, I wasn't aware of this in the beginning.

> I only implemented 2 because 1 was more complex to implement and also much harder for me to test.

I'm currently working on the this (without QRCode support only for entering it) one because I want my test result without wasting time at the doctor's office.
But I'm neither a Qt nor a SFOS expert, but at least I can test it in real :) I can't assign myself as a 3rd party, would be nice if you can do that.

> Are you certain that 2 has been deprecated? Or could it just be that you need to await the result before you can get hold of a TeleTAN? If indeed they have been deprecated, then I'd certainly have to look into implementing 1.

~~Afaik as I know from a Podcast, they were are temporary solution until the other thing works. You couldn't get the TeleTANs without extra effort, anyway.  The [corona-warn-app website](https://www.coronawarn.app/en/blog/2020-08-25-notes-qr-codes/) tells this:~~
Edit: You can still opt for TeleTAN via the telephone hotline. The other option is not necessary, TeleTAN remains active.

> Thanks for your input here, it's really appreciated. I hope your result is negative.
> 
> Another important point is that if you've been using Contrac, you should avoid scanning the QR code on an Android device that you've not been using, since this could result in the wrong keys being uploaded to the server.

I scanned the QR Code on SailfishOS, so nothing to worry about :) Tomorrow, when the doctor told me the test result will be there for sure, I'll ask to be 100%ly sure. But probably I don't have Covid, doctor didn't want to make a test be the laboratories are very busy again :(

**Comment by bionade24** [comment]
Now possible with #73
