### ISSUE TITLE
I'm receiving keys when i shouldn't (I believe)

### ISSUE THREAD

**Issue by Matzt** [llewelld/harbour-contrac#69]
Hi there,
I keep receiving keys when I'm in my flat although no one in my household has any corona-app installed. The closest people who could have a corona-app installed are my neighbors above me but between them are at least 3.5m distance and a ceiling or my neighbors from next door where a solid brick wall is in between. Since I live in a German "Altbau" it is possible that the ceiling only consists of wood, some insulation and plaster though. Nevertheless it seems weird receiving those keys.
My device is a Sony XA2 single sim, with SFOS 3.4.0.24 and contrac 0.7.4.

**Comment by llewelld** [comment]
I'm not sure this is so unlikely. Bluetooth Low Energy beacons can travel a surprising distance (in my own tests, up to 30-40 m away). They're passive and don't need to retain a connection, so are picked up surprisingly well. It's true that they'll be quite severely affected by obstacles, but I wouldn't be surprised at them being picked up between apartments, for example.

One thing to bear in mind is that any beacon detected will increase the counter. However, this doesn't mean that the beacon will contribute to the final risk calculation. A calculation based on the RSSI (received signal strength), as well as the transmit power of the sending device, is used to filter out distant packets. Packets with a stronger signal can be considered higher risk.

The actual weights of the calculation depend on values provided by the Corona-Warn-App servers. Since the weights aren't known until an update is performed, it's necessary to collect every beacon, even if it isn't ultimately used in the calculation.

Having said all that, if you're convinced that your device is picking up beacons when it shouldn't, we can look into it further (e.g. I can send you some diagnostic code to check the values you're receiving, etc.).

**Comment by Matzt** [comment]
Thanks for your detailed reply. This sounds very plausible to me and although (like I said already) I didn't expect this I'm convinced now. Sorry to take up your time, I should at least have looked shortly into this.

**Comment by llewelld** [comment]
That's good to hear, as it would have had me scratching my head otherwise.

Please don't apologise. It's always good to get feedback (in fact, the feedback has been absolutely essential so far), and without getting in to the code, there's no reason you should have known this. It will hopefully be useful for other users too.
