### ISSUE TITLE
Diagnosis Key download not working anymore

### ISSUE THREAD

**Issue by Matzt** [llewelld/harbour-contrac#82]
Since a few days I always get a network error whe trying to download tje diagnosis keys. I'm running  Contrac 0.7.5 on Xperia xa2 woth SFOS 3.4.0.24.
Restarting Contrac and phone didn't help, all other apps can use the Internet.

**Comment by llewelld** [comment]
Thanks for the report. This seems to be because the servers were changed so that they no longer supply hourly keys, but it's still possible to download daily key sets. I'll need to update the app and will roll out an update as soon as it's ready.

**Comment by llewelld** [comment]
This has been fixed with #83, released in version 0.7.6.

The fix was to download the daily archives rather than the hourly ones. As it happens, I noticed that the hourly archives are now being posted again. I'm not sure why there was an interruption. Still, it seems the daily archives are more robust, so better to stick with those from now on.

Thanks for the bug report. If you experience any other problems with this, please let us know.
